---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tikoapi
  name: tikoapi-service
  namespace: tikoapi
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '80'
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: tikoapi